services:
  home:
    image: nginx:alpine
    container_name: home
    ports:
      - "8000:80"
    volumes:
      - ./:/usr/share/nginx/html
    restart: always

  lab1:
    build: ./Lab1
    container_name: lab1
    ports:
      - "7001:5000"   # Flask inside runs on 5000
    restart: always

  lab2:
    build: ./Lab2
    container_name: lab2
    ports:
      - "7002:7000"   # Flask inside runs on 7000
    restart: always